/**
 * Full mock of Scale Result PDF — both variants (patient + therapist).
 * Uses the same layout code as the real builder, with mock data.
 */
import { jsPDF } from "jspdf";
import * as fs from "fs";
import { ICON_PNG_B64, WATERMARK_PNG_B64 } from "./src/features/activities/pdf-brand-assets.server";

const NAVY = [31, 42, 54] as const;
const CREAM = [244, 239, 230] as const;
const SAGE = [126, 155, 134] as const;
const CHARCOAL = [58, 63, 71] as const;
const WHITE = [255, 255, 255] as const;
const RED = [192, 57, 43] as const;

const M = 18;
const PAGE_W = 210;
const PAGE_H = 297;
const CW = PAGE_W - M * 2;
const FOOTER_ZONE = PAGE_H - 22;

type Variant = "patient" | "therapist";

interface ItemBreakdown {
  id: string;
  label: string;
  responseValue: number | null;
  points: number | null;
  weight: number;
  flagLabel: string | null;
}

function drawWatermark(doc: jsPDF) {
  const gs = (doc as any).GState;
  if (gs) {
    doc.saveGraphicsState();
    doc.setGState(new gs({ opacity: 0.045 }));
    const size = 120;
    doc.addImage(`data:image/png;base64,${WATERMARK_PNG_B64}`, "PNG", (PAGE_W - size) / 2, (PAGE_H - size) / 2, size, size);
    doc.restoreGraphicsState();
  }
}

function drawHeader(doc: jsPDF): number {
  const barH = 18;
  doc.setFillColor(...NAVY);
  doc.rect(0, 0, PAGE_W, barH, "F");
  const iconSize = 10;
  const iconY = (barH - iconSize) / 2;
  doc.addImage(`data:image/png;base64,${ICON_PNG_B64}`, "PNG", M, iconY, iconSize, iconSize);
  doc.setFont("times", "bold");
  doc.setFontSize(16);
  doc.setTextColor(...CREAM);
  const wmX = M + iconSize + 3;
  const wmY = barH / 2 + 2;
  doc.text("terapily", wmX, wmY);
  const dotX = wmX + doc.getTextWidth("terapily");
  doc.setTextColor(...SAGE);
  doc.text(".", dotX, wmY);
  return barH;
}

function drawFooter(doc: jsPDF, pageNum: number, totalPages: number, variant: Variant) {
  const fy = PAGE_H - 14;
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.3);
  doc.line(M, fy - 2, PAGE_W - M, fy - 2);
  const iconS = 4;
  doc.addImage(`data:image/png;base64,${ICON_PNG_B64}`, "PNG", M, fy - 0.5, iconS, iconS);
  doc.setFont("times", "bold");
  doc.setFontSize(7.5);
  doc.setTextColor(...NAVY);
  const wmX = M + iconS + 1.5;
  doc.text("terapily", wmX, fy + 2);
  doc.setTextColor(...SAGE);
  doc.text(".", wmX + doc.getTextWidth("terapily"), fy + 2);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(6.5);
  doc.setTextColor(...CHARCOAL);
  const yearX = wmX + doc.getTextWidth("terapily.") + 2;
  doc.text(`· ${new Date().getFullYear()}`, yearX, fy + 2);
  doc.setFontSize(7);
  const pg = `${pageNum} / ${totalPages}`;
  const pgW = doc.getTextWidth(pg);
  doc.text(pg, (PAGE_W - pgW) / 2, fy + 2);
  doc.setFontSize(5.5);
  doc.setTextColor(153, 153, 153);
  const disc = variant === "patient"
    ? "This document was generated by Terapily. It is not a diagnosis or treatment recommendation."
    : "Platform-generated scoring summary. Does not replace clinical documentation in your EHR.";
  const discW = doc.getTextWidth(disc);
  doc.text(disc, PAGE_W - M - discW, fy + 6);
}

function formatFullDateTime(iso: string): string {
  return new Date(iso).toLocaleString("en-US", {
    month: "short", day: "numeric", year: "numeric",
    hour: "2-digit", minute: "2-digit", timeZoneName: "short",
  });
}

// Mock PHQ-9 data
const ACTIVITY_TITLE = "PHQ-9 — Depressão";
const PHQ9_ITEMS: ItemBreakdown[] = [
  { id: "q1", label: "Little interest or pleasure in doing things", responseValue: 2, points: 2, weight: 1, flagLabel: null },
  { id: "q2", label: "Feeling down, depressed, or hopeless", responseValue: 2, points: 2, weight: 1, flagLabel: null },
  { id: "q3", label: "Trouble falling or staying asleep, or sleeping too much", responseValue: 1, points: 1, weight: 1, flagLabel: null },
  { id: "q4", label: "Feeling tired or having little energy", responseValue: 2, points: 2, weight: 1, flagLabel: null },
  { id: "q5", label: "Poor appetite or overeating", responseValue: 1, points: 1, weight: 1, flagLabel: null },
  { id: "q6", label: "Feeling bad about yourself — or that you are a failure", responseValue: 1, points: 1, weight: 1, flagLabel: null },
  { id: "q7", label: "Trouble concentrating on things, such as reading the newspaper", responseValue: 0, points: 0, weight: 1, flagLabel: null },
  { id: "q8", label: "Moving or speaking so slowly that other people could have noticed", responseValue: 0, points: 0, weight: 1, flagLabel: null },
  { id: "q9", label: "Thoughts that you would be better off dead, or of hurting yourself", responseValue: 1, points: 1, weight: 1, flagLabel: "suicidal_ideation" },
];

function buildPDF(variant: Variant): ArrayBuffer {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  let totalPages = 1;
  let currentPage = 1;
  const items = variant === "therapist" ? PHQ9_ITEMS : PHQ9_ITEMS.map(i => ({ ...i, flagLabel: null }));
  const score = 10;
  const maxPossibleScore = 27;
  const severity = "moderate";
  const maxStr = ` / ${maxPossibleScore}`;
  const hasPHI = variant === "therapist";
  const patientLabel = hasPHI ? "Maria Silva Santos" : "Maria S.";
  const scoringType = "sum";
  const submittedAt = "2026-04-30T14:22:00Z";

  function checkPage(y: number, needed = 10): number {
    if (y + needed > FOOTER_ZONE) {
      drawFooter(doc, currentPage, totalPages, variant);
      doc.addPage();
      currentPage++;
      drawWatermark(doc);
      return drawHeader(doc) + 9;
    }
    return y;
  }

  drawWatermark(doc);
  let y = drawHeader(doc);

  // Clinician band
  if (variant === "therapist") {
    const bandH = 10;
    doc.setFillColor(253, 232, 232);
    doc.rect(0, y, PAGE_W, bandH, "F");
    doc.setTextColor(...RED);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    const bl = "CLINICIAN COPY — NOT INTENDED FOR PATIENT DISTRIBUTION";
    doc.text(bl, (PAGE_W - doc.getTextWidth(bl)) / 2, y + bandH / 2 + 1.5);
    y += bandH;
  }

  y += 10;

  // Title
  doc.setTextColor(...NAVY);
  doc.setFont("times", "bold");
  doc.setFontSize(20);
  doc.text(variant === "patient" ? "Activity Result" : "Clinical Activity Result", M, y);
  y += 5;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...CHARCOAL);
  doc.text(variant === "patient" ? "Summary of your responses" : "Detailed scoring for your clinical records", M, y);
  y += 5;

  // PHI warning
  if (variant === "therapist" && hasPHI) {
    y += 2;
    doc.setFillColor(255, 243, 224);
    doc.roundedRect(M, y, CW, 8, 1.5, 1.5, "F");
    doc.setTextColor(230, 81, 0);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(7);
    doc.text("PHI WARNING:", M + 3, y + 5);
    doc.setFont("helvetica", "normal");
    doc.text("This document contains Protected Health Information. Store securely per your practice's policies.", M + 28, y + 5);
    y += 10;
  } else {
    y += 3;
  }

  // Info box
  const genStr = formatFullDateTime(new Date().toISOString());
  const infoItems: [string, string][] = [
    [variant === "patient" ? "Participant:" : "Patient:", patientLabel],
    ["Activity:", ACTIVITY_TITLE],
    ["Date:", formatFullDateTime(submittedAt)],
    ["Mode:", "shared link"],
  ];
  if (variant === "therapist") {
    infoItems.push(["Therapist:", "Dr. Ana Therapist"]);
    infoItems.push(["Practice:", "Wellness Clinic"]);
    infoItems.push(["License:", "PSY-12345"]);
    infoItems.push(["NPI:", "1234567890"]);
    infoItems.push(["Generated:", genStr]);
  } else {
    infoItems.push(["Generated:", genStr]);
  }

  const infoLineH = 6;
  const infoPadY = 6;
  const infoBoxH = infoPadY * 2 + infoItems.length * infoLineH;
  doc.setFillColor(247, 245, 240);
  doc.roundedRect(M, y, CW, infoBoxH, 2, 2, "F");
  let iy = y + infoPadY + 4;
  for (const [label, val] of infoItems) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(...NAVY);
    doc.text(label, M + 4, iy);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...CHARCOAL);
    doc.text(val, M + 30, iy);
    iy += infoLineH;
  }
  y += infoBoxH + 8;

  // Score box
  y = checkPage(y, 28);
  doc.setDrawColor(...SAGE);
  doc.setLineWidth(0.6);
  doc.setFillColor(247, 250, 248);
  doc.roundedRect(M, y, CW, variant === "therapist" ? 30 : 22, 2, 2, "FD");
  let ry = y + 7;
  doc.setTextColor(...NAVY);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text(variant === "patient" ? "Your Score:" : "Total Score:", M + 4, ry);
  doc.setFont("times", "bold");
  doc.setFontSize(18);
  doc.text(`${score}${maxStr}`, M + 40, ry);
  ry += 8;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...CHARCOAL);
  doc.text(`Band (per instrument definition): ${severity}`, M + 4, ry);

  if (variant === "therapist") {
    ry += 6;
    doc.text(`Items answered: 9 / 9 · Completion: 100%`, M + 4, ry);
  }
  y += (variant === "therapist" ? 30 : 22) + 8;

  // Item table
  y = checkPage(y, 30);
  doc.setTextColor(...NAVY);
  doc.setFont("times", "bold");
  doc.setFontSize(12);
  doc.text(variant === "patient" ? "Your Responses" : "Item-by-Item Breakdown", M, y);
  y += 7;

  const hasFlags = variant === "therapist" && items.some(it => it.flagLabel);
  const colX = hasFlags
    ? [M + 2, M + 10, M + 100, M + 130, M + 150]
    : [M + 2, M + 10, M + 110, M + 140];
  const headers = hasFlags
    ? ["#", "Item", "Response", "Points", "Flag"]
    : ["#", "Item", "Response", "Points"];

  const thH = 8;
  function drawTableHeader(atY: number): number {
    doc.setFillColor(...NAVY);
    doc.roundedRect(M, atY, CW, thH, 1, 1, "F");
    doc.setTextColor(...WHITE);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(7);
    const thY = atY + thH / 2 + 1.5;
    for (let h = 0; h < headers.length; h++) {
      doc.text(headers[h], colX[h], thY);
    }
    return atY + thH + 1;
  }

  y = drawTableHeader(y);

  const ROW_H = 8;
  for (let i = 0; i < items.length; i++) {
    if (y + ROW_H > FOOTER_ZONE) {
      drawFooter(doc, currentPage, totalPages, variant);
      doc.addPage();
      currentPage++;
      drawWatermark(doc);
      y = drawHeader(doc) + 9;
      y = drawTableHeader(y);
    }
    if (i % 2 === 0) {
      doc.setFillColor(249, 247, 243);
      doc.rect(M, y, CW, ROW_H, "F");
    }
    const item = items[i];
    const textY = y + ROW_H / 2 + 1;
    doc.setTextColor(...CHARCOAL);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.text(`${i + 1}`, colX[0], textY);
    const labelTrunc = item.label.length > 55 ? item.label.slice(0, 52) + "…" : item.label;
    doc.text(labelTrunc, colX[1], textY);
    doc.text(item.responseValue != null ? `${item.responseValue}` : "—", colX[2], textY);
    doc.setFont("helvetica", "bold");
    doc.text(item.points != null ? `${item.points}` : "—", colX[3], textY);
    if (hasFlags && item.flagLabel) {
      doc.setTextColor(...RED);
      doc.setFontSize(6.5);
      doc.text(`! ${item.flagLabel}`, colX[4], textY);
    }
    y += ROW_H;
  }

  // Total row
  y = checkPage(y, ROW_H + 2);
  doc.setFillColor(...SAGE);
  doc.roundedRect(M, y, CW, ROW_H, 1, 1, "F");
  doc.setTextColor(...WHITE);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  const totalTextY = y + ROW_H / 2 + 1.5;
  doc.text("TOTAL", colX[1], totalTextY);
  doc.text(`${score}${maxStr}`, colX[3], totalTextY);
  y += ROW_H + 6;

  // Scoring transparency (therapist)
  if (variant === "therapist") {
    y = checkPage(y, 30);
    doc.setTextColor(...NAVY);
    doc.setFont("times", "bold");
    doc.setFontSize(12);
    doc.text("Scoring Transparency", M, y);
    y += 7;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...CHARCOAL);
    doc.text(`Scoring method: Sum`, M, y); y += 5;
    doc.text(`Instrument: ${ACTIVITY_TITLE}`, M, y); y += 5;
    doc.text("Defined bands:", M, y); y += 5;
    const bands = [
      { min: 0, max: 4, label: "minimal" },
      { min: 5, max: 9, label: "mild" },
      { min: 10, max: 14, label: "moderate" },
      { min: 15, max: 19, label: "moderately_severe" },
      { min: 20, max: 27, label: "severe" },
    ];
    for (const band of bands) {
      doc.text(`  ${band.min}–${band.max}: ${band.label}`, M + 4, y);
      y += 4;
    }
    y += 3;
  }

  // Clinical flags (therapist)
  if (variant === "therapist") {
    const flaggedItems = items.filter(it => it.flagLabel);
    if (flaggedItems.length > 0) {
      y = checkPage(y, 20);
      doc.setTextColor(...NAVY);
      doc.setFont("times", "bold");
      doc.setFontSize(12);
      doc.text("Clinical Flags", M, y);
      y += 7;
      for (const fi of flaggedItems) {
        y = checkPage(y, 12);
        doc.setFillColor(255, 243, 224);
        doc.roundedRect(M, y, CW, 10, 1.5, 1.5, "F");
        doc.setTextColor(230, 81, 0);
        doc.setFont("helvetica", "bold");
        doc.setFontSize(7.5);
        doc.text(`! ${fi.flagLabel}`, M + 3, y + 4);
        doc.setFont("helvetica", "normal");
        doc.setFontSize(7);
        doc.setTextColor(...CHARCOAL);
        doc.text(`Item: ${fi.label} · Response value: ${fi.responseValue}`, M + 3, y + 8);
        y += 12;
      }
      y += 4;
    }
  }

  // Important Notice / Notices
  y = checkPage(y, 40);
  if (variant === "patient") {
    const padX = 6;
    const padTop = 7;
    const padBottom = 7;
    const titleLineH = 6;
    const bodyLineH = 4;
    const bodyLines = [
      `The score presented above reflects your responses to a validated clinical instrument`,
      `(${ACTIVITY_TITLE}) and is provided for informational purposes only. It does not`,
      `constitute a diagnosis, clinical assessment, or treatment recommendation.`,
      ``,
      `Please discuss these results with your therapist or a qualified mental health professional.`,
      ``,
      `This document does not replace a clinical evaluation.`,
    ];
    const noticeH = padTop + titleLineH + bodyLines.length * bodyLineH + padBottom;
    doc.setFillColor(255, 248, 225);
    doc.roundedRect(M, y, CW, noticeH, 2, 2, "F");
    doc.setDrawColor(240, 208, 96);
    doc.setLineWidth(0.4);
    doc.roundedRect(M, y, CW, noticeH, 2, 2, "S");
    let ny = y + padTop;
    doc.setTextColor(...NAVY);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.text("Important Notice", M + padX, ny);
    ny += titleLineH;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    doc.setTextColor(...CHARCOAL);
    for (const line of bodyLines) { doc.text(line, M + padX, ny); ny += bodyLineH; }
  } else {
    doc.setTextColor(...NAVY);
    doc.setFont("times", "bold");
    doc.setFontSize(12);
    doc.text("Notices", M, y);
    y += 7;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    doc.setTextColor(...CHARCOAL);
    const notices = [
      `This document is a platform-generated scoring summary for ${ACTIVITY_TITLE}. ` +
      `Scores are computed using the instrument's published scoring algorithm. ` +
      `Item-level data is provided for transparency. ` +
      `Clinical interpretation remains the sole responsibility of the treating clinician.`,
      ``,
      `Follow applicable legal and professional guidelines.`,
    ];
    for (const notice of notices) {
      const wrapped = doc.splitTextToSize(notice, CW - 2);
      for (const line of wrapped) {
        y = checkPage(y, 5);
        doc.setTextColor(...CHARCOAL);
        doc.setFont("helvetica", "normal");
        doc.setFontSize(7.5);
        doc.text(line, M, y);
        y += 4;
      }
    }
  }

  // Footer
  drawFooter(doc, currentPage, totalPages, variant);

  // Fix page count
  totalPages = currentPage;
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let p = 1; p <= pageCount; p++) {
    doc.setPage(p);
    doc.setFillColor(255, 255, 255);
    doc.rect(PAGE_W / 2 - 15, PAGE_H - 16, 30, 6, "F");
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(...CHARCOAL);
    const pg = `${p} / ${totalPages}`;
    const pgW = doc.getTextWidth(pg);
    doc.text(pg, (PAGE_W - pgW) / 2, PAGE_H - 12);
  }

  return doc.output("arraybuffer");
}

// Generate both
const patientBuf = buildPDF("patient");
fs.writeFileSync("/mnt/documents/scale-result-patient-full.pdf", Buffer.from(patientBuf));

const therapistBuf = buildPDF("therapist");
fs.writeFileSync("/mnt/documents/scale-result-therapist-full.pdf", Buffer.from(therapistBuf));

console.log("Both PDFs generated.");
