import { jsPDF } from "jspdf";
import { writeFileSync } from "fs";
import { ICON_PNG_B64, WATERMARK_PNG_B64 } from "./src/features/activities/pdf-brand-assets.server";
const NAVY=[31,42,54] as const,CREAM=[244,239,230] as const,SAGE=[126,155,134] as const,CHARCOAL=[58,63,71] as const,WHITE=[255,255,255] as const,RED=[192,57,43] as const;
const M=18,PAGE_W=210,PAGE_H=297,CW=PAGE_W-M*2,FOOTER_ZONE=PAGE_H-22,CONTENT_GAP=9,integrityHash="a3f8c1e2…";
function drawWatermark(d:jsPDF){const gs=(d as any).GState;if(gs){d.saveGraphicsState();d.setGState(new gs({opacity:0.045}));d.addImage(`data:image/png;base64,${WATERMARK_PNG_B64}`,"PNG",(PAGE_W-120)/2,(PAGE_H-120)/2,120,120);d.restoreGraphicsState();}}
function drawHeader(d:jsPDF){const barH=18;d.setFillColor(...NAVY);d.rect(0,0,PAGE_W,barH,"F");d.addImage(`data:image/png;base64,${ICON_PNG_B64}`,"PNG",M,(barH-10)/2,10,10);d.setFont("times","bold");d.setFontSize(16);d.setTextColor(...CREAM);const wx=M+13,wy=barH/2+2;d.text("terapily",wx,wy);d.setTextColor(...SAGE);d.text(".",wx+d.getTextWidth("terapily"),wy);return barH;}
function drawFooter(d:jsPDF,p:number,t:number){const fy=PAGE_H-14;d.setDrawColor(200,200,200);d.setLineWidth(0.3);d.line(M,fy-2,PAGE_W-M,fy-2);d.addImage(`data:image/png;base64,${ICON_PNG_B64}`,"PNG",M,fy-0.5,4,4);d.setFont("times","bold");d.setFontSize(7.5);d.setTextColor(...NAVY);const wx=M+5.5;d.text("terapily",wx,fy+2);d.setTextColor(...SAGE);d.text(".",wx+d.getTextWidth("terapily"),fy+2);d.setFont("helvetica","normal");d.setFontSize(6.5);d.setTextColor(...CHARCOAL);d.text(`· ${new Date().getFullYear()}`,wx+d.getTextWidth("terapily.")+2,fy+2);d.setFontSize(7);const pg=`${p} / ${t}`;d.text(pg,(PAGE_W-d.getTextWidth(pg))/2,fy+2);d.setFontSize(5.5);d.setTextColor(153,153,153);const disc="Platform-generated summary. Does not replace clinical documentation in your EHR.";d.text(disc,PAGE_W-M-d.getTextWidth(disc),fy+6);d.setFontSize(5);d.text(`Report ID: ${integrityHash}`,M,fy+6);}
let cp=1;function np(d:jsPDF){d.addPage();cp++;drawWatermark(d);return drawHeader(d)+CONTENT_GAP;}
function ck(d:jsPDF,y:number,n:number){return y+n>FOOTER_ZONE?np(d):y;}

const doc=new jsPDF({orientation:"portrait",unit:"mm",format:"a4"});drawWatermark(doc);let y=drawHeader(doc);
// Band
const bandH=10;doc.setFillColor(253,232,232);doc.rect(0,y,PAGE_W,bandH,"F");doc.setTextColor(...RED);doc.setFont("helvetica","bold");doc.setFontSize(8);const bl="CLINICIAN COPY — NOT INTENDED FOR PATIENT DISTRIBUTION";doc.text(bl,(PAGE_W-doc.getTextWidth(bl))/2,y+bandH/2+1.5);y+=bandH+12;
// Title
doc.setTextColor(...NAVY);doc.setFont("times","bold");doc.setFontSize(20);doc.text("Clinical Activity Report",M,y);y+=5;doc.setFont("helvetica","normal");doc.setFontSize(9);doc.setTextColor(...CHARCOAL);doc.text("Summary of recorded activities for your clinical records",M,y);y+=5;
// PHI
y+=2;doc.setFillColor(255,243,224);doc.roundedRect(M,y,CW,8,1.5,1.5,"F");doc.setTextColor(230,81,0);doc.setFont("helvetica","bold");doc.setFontSize(7);doc.text("PHI WARNING:",M+3,y+5);doc.setFont("helvetica","normal");doc.text("This document contains Protected Health Information. Store securely per your practice's HIPAA policies.",M+28,y+5);y+=10;
// Info
const ii:[string,string][]=[["Patient:","Jane D. (JD)"],["Therapist:","Dr. Sarah Mitchell, LCSW"],["Practice:","Clarity Behavioral Health"],["Period:","3/1/2026 — 5/1/2026"],["Generated:","May 1, 2026, 04:30 PM UTC"],["License:","LCSW-48291"],["NPI:","1234567890"]];
const ilh=6,ipy=6,ibh=ipy*2+ii.length*ilh;doc.setFillColor(247,245,240);doc.roundedRect(M,y,CW,ibh,2,2,"F");let iy2=y+ipy+4;for(const[l,v]of ii){doc.setFont("helvetica","bold");doc.setFontSize(10);doc.setTextColor(...NAVY);doc.text(l,M+4,iy2);doc.setFont("helvetica","normal");doc.setTextColor(...CHARCOAL);doc.text(v,M+28,iy2);iy2+=ilh;}y+=ibh+8;
// Quick Read — measure first, draw box, then render content
const se=[{title:"PHQ-9",score:14,severity:"Moderate",delta:-3},{title:"GAD-7",score:10,severity:"Moderate",delta:+2},{title:"PCL-5",score:38,severity:"Above threshold",delta:-5}];
const qlh=5,qhh=12;
// Measure
const qStartY=y;let mqy=y+qhh+2;for(const e of se){mqy+=e.severity?qlh+3.5:qlh;}const qEndY=mqy+8;const mBoxH=qEndY-qStartY;
// Draw box
doc.setDrawColor(...NAVY);doc.setLineWidth(0.5);doc.setFillColor(250,248,244);doc.roundedRect(M,y,CW,mBoxH,2,2,"FD");
// Header
doc.setFont("helvetica","bold");doc.setFontSize(10);doc.setTextColor(...NAVY);doc.text("Quick Read",M+4,y+6);doc.setFont("helvetica","normal");doc.setFontSize(7);doc.setTextColor(...CHARCOAL);doc.text("Data index — not a clinical summary.",M+30,y+6);
// Content
let qy=y+qhh+2;for(const e of se){doc.setFont("helvetica","normal");doc.setFontSize(8);doc.setTextColor(...CHARCOAL);let ln=`${e.title}: ${e.score}`;if(e.delta!==0){const s=e.delta>0?"+":"",a=e.delta>0?"(+)":"(-)";ln+=` · ${a} ${s}${e.delta} points`;}doc.text(ln,M+4,qy);if(e.severity){doc.setFontSize(6.5);doc.setTextColor(130,130,130);doc.text(`Severity: ${e.severity} (scale-defined)`,M+4,qy+3.5);doc.setTextColor(...CHARCOAL);doc.setFontSize(8);}qy+=e.severity?qlh+3.5:qlh;}
doc.setFont("helvetica","italic");doc.setFontSize(5.5);doc.setTextColor(150,150,150);doc.text("Changes reflect score differences only and do not imply clinical improvement or worsening.",M+4,qy+1);
y=qEndY;
// Activity History — with CONTENT_GAP
y+=CONTENT_GAP;y=ck(doc,y,30);doc.setTextColor(...NAVY);doc.setFont("times","bold");doc.setFontSize(12);doc.text("Activity History",M,y);y+=8;
const thH=10;doc.setFillColor(...NAVY);doc.roundedRect(M,y,CW,thH,1,1,"F");const cols=[M+4,M+42,M+90,M+112,M+130,M+158];doc.setTextColor(...WHITE);doc.setFont("helvetica","bold");doc.setFontSize(7);["DATE","ACTIVITY","MODE","SCORE","SEVERITY","FLAG"].forEach((h,i)=>doc.text(h,cols[i],y+thH/2+1.5));y+=thH+2;
const sr=[{date:"Apr 28, 2026, 02:15 PM UTC",title:"PHQ-9",mode:"in session",score:"14",severity:"Moderate",flag:false},{date:"Apr 21, 2026, 10:30 AM UTC",title:"PHQ-9",mode:"shared link",score:"17",severity:"Mod. Severe",flag:true},{date:"Apr 14, 2026, 03:45 PM UTC",title:"GAD-7",mode:"in session",score:"10",severity:"Moderate",flag:false},{date:"Apr 7, 2026, 11:00 AM UTC",title:"GAD-7",mode:"shared link",score:"8",severity:"Mild",flag:false},{date:"Mar 28, 2026, 09:30 AM UTC",title:"PCL-5",mode:"in session",score:"38",severity:"Above threshold",flag:true},{date:"Mar 14, 2026, 02:00 PM UTC",title:"PCL-5",mode:"in session",score:"43",severity:"Above threshold",flag:true}];
const RH=12;for(let i=0;i<sr.length;i++){y=ck(doc,y,RH);const r=sr[i];if(i%2===0){doc.setFillColor(249,247,243);doc.rect(M,y,CW,RH,"F");}const tY=y+RH/2+1;doc.setTextColor(...CHARCOAL);doc.setFont("helvetica","normal");doc.setFontSize(7);doc.text(r.date,cols[0],tY);doc.setFontSize(9);doc.text(r.title,cols[1],tY);doc.text(r.mode,cols[2],tY);doc.setFont("helvetica","bold");doc.setFontSize(10);doc.text(r.score,cols[3],tY);doc.setFont("helvetica","normal");doc.text(r.severity,cols[4],tY);if(r.flag){doc.setTextColor(...RED);doc.setFont("helvetica","bold");doc.setFontSize(8);doc.text("FLAG",cols[5],tY);}y+=RH;}
// Score History
y+=10;y=ck(doc,y,60);doc.setTextColor(...NAVY);doc.setFont("times","bold");doc.setFontSize(12);doc.text("Score History",M,y);y+=8;
const sd=[{title:"PHQ-9",points:[{date:"Mar 14",score:20},{date:"Mar 28",score:18},{date:"Apr 14",score:17},{date:"Apr 28",score:14}],yMax:27,delta:-3},{title:"GAD-7",points:[{date:"Mar 14",score:6},{date:"Mar 28",score:7},{date:"Apr 7",score:8},{date:"Apr 14",score:10}],yMax:13,delta:+2}];
for(const s of sd){const gh=40,gw=CW-20;y=ck(doc,y,gh+18);doc.setTextColor(...NAVY);doc.setFont("helvetica","bold");doc.setFontSize(9);doc.text(s.title,M,y);if(s.delta!==0){const sg=s.delta>0?"+":"",ar=s.delta>0?"(+)":"(-)";doc.setFont("helvetica","normal");doc.setFontSize(8);doc.text(`${ar} ${sg}${s.delta} points`,M+doc.getTextWidth(s.title)+8,y);}y+=5;const gx=M+10,gy=y;doc.setDrawColor(220,220,220);doc.setLineWidth(0.2);for(let g=0;g<=3;g++)doc.line(gx,gy+(gh*g)/3,gx+gw,gy+(gh*g)/3);doc.setFont("helvetica","normal");doc.setFontSize(6);doc.setTextColor(150,150,150);for(let g=0;g<=3;g++)doc.text(`${Math.round(s.yMax*(1-g/3))}`,M,gy+(gh*g)/3+1.5);const xs=s.points.length>1?gw/(s.points.length-1):0;const co=s.points.map((p,i)=>({px:gx+i*xs,py:gy+gh-(p.score/s.yMax)*gh}));doc.setDrawColor(...SAGE);doc.setLineWidth(0.8);for(let i=1;i<co.length;i++)doc.line(co[i-1].px,co[i-1].py,co[i].px,co[i].py);for(let i=0;i<co.length;i++){const{px,py}=co[i];const il=i===co.length-1;const r=il?2:1.2;doc.setFillColor(...SAGE);doc.circle(px,py,r,"F");if(il){doc.setDrawColor(...WHITE);doc.setLineWidth(0.5);doc.circle(px,py,r+0.5,"S");}}doc.setFont("helvetica","normal");doc.setFontSize(6);doc.setTextColor(150,150,150);for(let i=0;i<s.points.length;i++){const l=s.points[i].date;doc.text(l,co[i].px-doc.getTextWidth(l)/2,gy+gh+4);}doc.setFontSize(7);doc.setTextColor(...NAVY);for(let i=0;i<s.points.length;i++){const l=`${s.points[i].score}`;doc.text(l,co[i].px-doc.getTextWidth(l)/2,co[i].py-3);}y=gy+gh+10;}
doc.setFont("helvetica","italic");doc.setFontSize(6);doc.setTextColor(150,150,150);doc.text("Displayed for documentation purposes only. No clinical interpretation is provided.",M,y);y+=6;
// Score Changes
const ce=[{title:"PHQ-9",prev:17,curr:14,delta:-3},{title:"GAD-7",prev:8,curr:10,delta:+2},{title:"PCL-5",prev:43,curr:38,delta:-5}];y+=4;y=ck(doc,y,30);doc.setTextColor(...NAVY);doc.setFont("helvetica","bold");doc.setFontSize(10);doc.text("Score Changes",M,y);y+=6;for(const c of ce){y=ck(doc,y,5);doc.setTextColor(...CHARCOAL);doc.setFont("helvetica","normal");doc.setFontSize(8);const sg=c.delta>0?"+":"",ar=c.delta>0?"(+)":"(-)";doc.text(`${c.title}: ${c.prev} > ${c.curr} (${ar} ${sg}${c.delta} points)`,M,y);y+=5;}
// Flags
y+=6;y=ck(doc,y,30);doc.setTextColor(...NAVY);doc.setFont("times","bold");doc.setFontSize(12);doc.text("Clinical Flag Timeline",M,y);y+=8;
const fl=[{status:"ACTIVE",date:"Apr 21, 2026, 10:30 AM UTC",desc:"PHQ-9: Item 9 score >= 1 (suicidal ideation screening)"},{status:"MONITORING",date:"Mar 28, 2026, 09:30 AM UTC",desc:"PCL-5: Total score 38 (above clinical threshold of 33)"},{status:"ACKNOWLEDGED",date:"Mar 14, 2026, 02:00 PM UTC",desc:"PCL-5: Total score 43 (above clinical threshold of 33)"}];
for(const f of fl){const FH=20;y=ck(doc,y,FH+3);const sc:any={ACTIVE:[192,57,43],MONITORING:[230,126,34],ACKNOWLEDGED:SAGE};const bg:any={ACTIVE:[253,232,232],MONITORING:[255,248,225],ACKNOWLEDGED:[237,245,239]};const bd:any={ACTIVE:[240,180,180],MONITORING:[240,208,96],ACKNOWLEDGED:[180,210,190]};doc.setFillColor(...(bg[f.status]??[249,247,243]));doc.roundedRect(M,y,CW,FH,1.5,1.5,"F");doc.setDrawColor(...(bd[f.status]??[200,200,200]));doc.setLineWidth(0.3);doc.roundedRect(M,y,CW,FH,1.5,1.5,"S");const ft=y+5;doc.setTextColor(...(sc[f.status]??CHARCOAL));doc.setFont("helvetica","bold");doc.setFontSize(8);doc.text(f.status,M+3,ft);doc.setTextColor(...CHARCOAL);doc.setFont("helvetica","normal");doc.setFontSize(7.5);doc.text(f.date,M+35,ft);doc.setFontSize(7);doc.text(f.desc,M+3,ft+5);doc.setTextColor(180,155,100);doc.setFontSize(5.5);doc.setFont("helvetica","italic");doc.text("This flag indicates a response that may be clinically relevant. Consult your jurisdiction's applicable laws and your professional ethical guidelines.",M+3,ft+10);y+=FH+3;}
// Audit
y+=6;y=ck(doc,y,80);doc.setTextColor(...NAVY);doc.setFont("times","bold");doc.setFontSize(12);doc.text("Audit Trail",M,y);y+=8;const ath=10;doc.setFillColor(...NAVY);doc.roundedRect(M,y,CW,ath,1,1,"F");doc.setTextColor(...WHITE);doc.setFont("helvetica","bold");doc.setFontSize(8);doc.text("TIMESTAMP",M+4,y+ath/2+1.5);doc.text("ACTION",M+55,y+ath/2+1.5);doc.text("ACTOR",M+120,y+ath/2+1.5);y+=ath+2;
const ar2=[{ts:"Apr 28, 2026, 02:15 PM UTC",act:"activity_response.submitted",ac:"Dr. Sarah Mitchell"},{ts:"Apr 21, 2026, 10:30 AM UTC",act:"activity_response.submitted",ac:"Patient (magic link)"},{ts:"Apr 21, 2026, 10:00 AM UTC",act:"patient_activity.created",ac:"Dr. Sarah Mitchell"},{ts:"Apr 14, 2026, 03:45 PM UTC",act:"activity_response.submitted",ac:"Dr. Sarah Mitchell"},{ts:"Mar 28, 2026, 09:30 AM UTC",act:"activity_response.submitted",ac:"Dr. Sarah Mitchell"},{ts:"Mar 14, 2026, 02:00 PM UTC",act:"activity_response.submitted",ac:"Dr. Sarah Mitchell"}];
for(let i=0;i<ar2.length;i++){const ARH=10;y=ck(doc,y,ARH);if(i%2===0){doc.setFillColor(249,247,243);doc.rect(M,y,CW,ARH,"F");}const atY=y+ARH/2+1;doc.setTextColor(...CHARCOAL);doc.setFont("helvetica","normal");doc.setFontSize(7);doc.text(ar2[i].ts,M+4,atY);doc.setFontSize(8);doc.text(ar2[i].act,M+55,atY);doc.text(ar2[i].ac,M+120,atY);y+=ARH;}
// Notices
y+=8;y=ck(doc,y,20);doc.setTextColor(...NAVY);doc.setFont("times","bold");doc.setFontSize(14);doc.text("Notices & Disclaimers",M,y);y+=7;
const nn:[string,string][]=[["Document Purpose","This Clinical Activity Report is a platform-generated summary of activities completed through Terapily. It is intended to support — not replace — clinical documentation maintained in your electronic health record (EHR). All clinical interpretations, diagnoses, and treatment decisions remain the sole responsibility of the treating clinician."],["Scoring Methodology","Scores are computed automatically using published scoring algorithms for each validated instrument. Item-level breakdowns are provided for transparency and auditability. Terapily does not modify, adjust, or interpret scores beyond the instrument's defined calculation."],["Clinical Flags","Clinical flags are generated when individual item responses meet predefined thresholds. Flags are informational alerts and do not constitute clinical advice. The treating clinician is responsible for determining appropriate follow-up in accordance with applicable laws and professional ethical guidelines."],["Data Integrity",`This report includes a Report ID (${integrityHash}) computed from report content at generation time. Full hash-chain verification will be available in a future platform update.`],["Protected Health Information","This document may contain Protected Health Information (PHI) as defined by HIPAA. It should be stored, transmitted, and disposed of in accordance with your practice's privacy and security policies. Terapily encrypts PHI at rest within the platform; once exported as PDF, security responsibility transfers to the recipient."],["Right of Access","Under HIPAA and the 21st Century Cures Act, patients have the right to request access to their health information. If a patient requests access, provide the Patient Activity Summary version, which excludes clinical flags, severity classifications, and clinician-only annotations."]];
for(const[t,b]of nn){y=ck(doc,y,14);doc.setTextColor(...NAVY);doc.setFont("helvetica","bold");doc.setFontSize(9);doc.text(t,M,y);y+=5;doc.setTextColor(...CHARCOAL);doc.setFont("helvetica","normal");doc.setFontSize(7.5);const ls=doc.splitTextToSize(b,CW-2);for(const l of ls){y=ck(doc,y,5);doc.setTextColor(...CHARCOAL);doc.setFont("helvetica","normal");doc.setFontSize(7.5);doc.text(l,M,y);y+=4;}y+=3;}
const tp=(doc as any).internal.getNumberOfPages();for(let p=1;p<=tp;p++){doc.setPage(p);drawFooter(doc,p,tp);}
writeFileSync("/mnt/documents/clinical-activity-report-v9b.pdf",Buffer.from(doc.output("arraybuffer")));console.log("PDF:",tp,"pages");
