import { jsPDF } from "jspdf";
import * as fs from "fs";
import { ICON_PNG_B64, WATERMARK_PNG_B64 } from "./src/features/activities/pdf-brand-assets.server";

const NAVY = [31, 42, 54] as const;
const CREAM = [244, 239, 230] as const;
const SAGE = [126, 155, 134] as const;
const CHARCOAL = [58, 63, 71] as const;
const WHITE = [255, 255, 255] as const;
const RED = [192, 57, 43] as const;
const M = 18;
const PAGE_W = 210;
const PAGE_H = 297;
const CW = PAGE_W - M * 2;
const FOOTER_ZONE = PAGE_H - 22;

type V = "patient" | "therapist";

interface Item { id: string; label: string; responseValue: number | null; points: number | null; weight: number; flagLabel: string | null; }

function drawWatermark(d: jsPDF) { const gs=(d as any).GState;if(gs){d.saveGraphicsState();d.setGState(new gs({opacity:0.045}));d.addImage(`data:image/png;base64,${WATERMARK_PNG_B64}`,"PNG",(PAGE_W-120)/2,(PAGE_H-120)/2,120,120);d.restoreGraphicsState();}}
function drawHeader(d: jsPDF): number { const h=18;d.setFillColor(...NAVY);d.rect(0,0,PAGE_W,h,"F");d.addImage(`data:image/png;base64,${ICON_PNG_B64}`,"PNG",M,(h-10)/2,10,10);d.setFont("times","bold");d.setFontSize(16);d.setTextColor(...CREAM);const x=M+13;d.text("terapily",x,h/2+2);d.setTextColor(...SAGE);d.text(".",x+d.getTextWidth("terapily"),h/2+2);return h;}
function drawFooter(d: jsPDF,p:number,t:number,v:V){const fy=PAGE_H-14;d.setDrawColor(200,200,200);d.setLineWidth(0.3);d.line(M,fy-2,PAGE_W-M,fy-2);d.addImage(`data:image/png;base64,${ICON_PNG_B64}`,"PNG",M,fy-0.5,4,4);d.setFont("times","bold");d.setFontSize(7.5);d.setTextColor(...NAVY);d.text("terapily",M+5.5,fy+2);d.setTextColor(...SAGE);d.text(".",M+5.5+d.getTextWidth("terapily"),fy+2);d.setFont("helvetica","normal");d.setFontSize(6.5);d.setTextColor(...CHARCOAL);d.text(`· ${new Date().getFullYear()}`,M+5.5+d.getTextWidth("terapily.")+2,fy+2);d.setFontSize(7);const pg=`${p} / ${t}`;d.text(pg,(PAGE_W-d.getTextWidth(pg))/2,fy+2);d.setFontSize(5.5);d.setTextColor(153,153,153);const disc=v==="patient"?"This document was generated by Terapily. It is not a diagnosis or treatment recommendation.":"Platform-generated scoring summary. Does not replace clinical documentation in your EHR.";d.text(disc,PAGE_W-M-d.getTextWidth(disc),fy+6);}
function fmtDT(iso:string){return new Date(iso).toLocaleString("en-US",{month:"short",day:"numeric",year:"numeric",hour:"2-digit",minute:"2-digit",timeZoneName:"short"});}

const TITLE = "PHQ-9 — Depressão";
const ITEMS: Item[] = [
  {id:"q1",label:"Little interest or pleasure in doing things",responseValue:2,points:2,weight:1,flagLabel:null},
  {id:"q2",label:"Feeling down, depressed, or hopeless",responseValue:2,points:2,weight:1,flagLabel:null},
  {id:"q3",label:"Trouble falling or staying asleep, or sleeping too much",responseValue:1,points:1,weight:1,flagLabel:null},
  {id:"q4",label:"Feeling tired or having little energy",responseValue:2,points:2,weight:1,flagLabel:null},
  {id:"q5",label:"Poor appetite or overeating",responseValue:1,points:1,weight:1,flagLabel:null},
  {id:"q6",label:"Feeling bad about yourself — or that you are a failure",responseValue:1,points:1,weight:1,flagLabel:null},
  {id:"q7",label:"Trouble concentrating on things, such as reading the newspaper",responseValue:0,points:0,weight:1,flagLabel:null},
  {id:"q8",label:"Moving or speaking so slowly that other people could have noticed",responseValue:0,points:0,weight:1,flagLabel:null},
  {id:"q9",label:"Thoughts that you would be better off dead, or of hurting yourself",responseValue:1,points:1,weight:1,flagLabel:"suicidal_ideation"},
];

function build(variant: V): ArrayBuffer {
  const doc = new jsPDF({orientation:"portrait",unit:"mm",format:"a4"});
  let totalPages=1, currentPage=1;
  const items = variant==="therapist" ? ITEMS : ITEMS.map(i=>({...i,flagLabel:null}));
  const score=10, maxPS=27, severity="moderate", maxStr=` / ${maxPS}`;
  const hasPHI=variant==="therapist", patientLabel=hasPHI?"Maria Silva Santos":"Maria S.";
  const submittedAt="2026-04-30T14:22:00Z";

  function checkPage(y:number,n=10){if(y+n>FOOTER_ZONE){drawFooter(doc,currentPage,totalPages,variant);doc.addPage();currentPage++;drawWatermark(doc);return drawHeader(doc)+9;}return y;}

  drawWatermark(doc);
  let y=drawHeader(doc);

  if(variant==="therapist"){const bH=10;doc.setFillColor(253,232,232);doc.rect(0,y,PAGE_W,bH,"F");doc.setTextColor(...RED);doc.setFont("helvetica","bold");doc.setFontSize(8);const bl="CLINICIAN COPY — NOT INTENDED FOR PATIENT DISTRIBUTION";doc.text(bl,(PAGE_W-doc.getTextWidth(bl))/2,y+bH/2+1.5);y+=bH;}
  y+=10;
  doc.setTextColor(...NAVY);doc.setFont("times","bold");doc.setFontSize(20);doc.text(variant==="patient"?"Activity Result":"Clinical Activity Result",M,y);y+=5;
  doc.setFont("helvetica","normal");doc.setFontSize(9);doc.setTextColor(...CHARCOAL);doc.text(variant==="patient"?"Summary of your responses":"Detailed scoring for your clinical records",M,y);y+=5;

  if(variant==="therapist"&&hasPHI){y+=2;doc.setFillColor(255,243,224);doc.roundedRect(M,y,CW,8,1.5,1.5,"F");doc.setTextColor(230,81,0);doc.setFont("helvetica","bold");doc.setFontSize(7);doc.text("PHI WARNING:",M+3,y+5);doc.setFont("helvetica","normal");doc.text("This document contains Protected Health Information. Store securely per your practice's policies.",M+28,y+5);y+=10;}else{y+=3;}

  const genStr=fmtDT(new Date().toISOString());
  const infoItems:[string,string][] = [[variant==="patient"?"Participant:":"Patient:",patientLabel],["Activity:",TITLE],["Date:",fmtDT(submittedAt)],["Mode:","shared link"]];
  if(variant==="therapist"){infoItems.push(["Therapist:","Dr. Ana Therapist"],["Practice:","Wellness Clinic"],["License:","PSY-12345"],["NPI:","1234567890"],["Generated:",genStr]);}else{infoItems.push(["Generated:",genStr]);}
  const iLH=6,iPY=6,iBH=iPY*2+infoItems.length*iLH;
  doc.setFillColor(247,245,240);doc.roundedRect(M,y,CW,iBH,2,2,"F");
  let iy=y+iPY+4;
  for(const[l,v2]of infoItems){doc.setFont("helvetica","bold");doc.setFontSize(9);doc.setTextColor(...NAVY);doc.text(l,M+4,iy);doc.setFont("helvetica","normal");doc.setTextColor(...CHARCOAL);doc.text(v2,M+30,iy);iy+=iLH;}
  y+=iBH+8;

  y=checkPage(y,28);doc.setDrawColor(...SAGE);doc.setLineWidth(0.6);doc.setFillColor(247,250,248);doc.roundedRect(M,y,CW,variant==="therapist"?30:22,2,2,"FD");
  let ry=y+7;doc.setTextColor(...NAVY);doc.setFont("helvetica","bold");doc.setFontSize(11);doc.text(variant==="patient"?"Your Score:":"Total Score:",M+4,ry);doc.setFont("times","bold");doc.setFontSize(18);doc.text(`${score}${maxStr}`,M+40,ry);ry+=8;
  doc.setFont("helvetica","normal");doc.setFontSize(9);doc.setTextColor(...CHARCOAL);doc.text(`Band (per instrument definition): ${severity}`,M+4,ry);
  if(variant==="therapist"){ry+=6;doc.text(`Items answered: 9 / 9 · Completion: 100%`,M+4,ry);}
  y+=(variant==="therapist"?30:22)+8;

  // Table
  y=checkPage(y,30);doc.setTextColor(...NAVY);doc.setFont("times","bold");doc.setFontSize(12);doc.text(variant==="patient"?"Your Responses":"Item-by-Item Breakdown",M,y);y+=7;
  const hasFlags=variant==="therapist"&&items.some(it=>it.flagLabel);
  const colX=hasFlags?[M+2,M+10,M+100,M+130,M+150]:[M+2,M+10,M+110,M+140];
  const headers=hasFlags?["#","Item","Response","Points","Flag"]:["#","Item","Response","Points"];
  const thH=8;
  function drawTH(atY:number){doc.setFillColor(...NAVY);doc.roundedRect(M,atY,CW,thH,1,1,"F");doc.setTextColor(...WHITE);doc.setFont("helvetica","bold");doc.setFontSize(7);const thY=atY+thH/2+1.5;for(let h=0;h<headers.length;h++)doc.text(headers[h],colX[h],thY);return atY+thH+1;}
  y=drawTH(y);
  const RH=8;
  for(let i=0;i<items.length;i++){if(y+RH>FOOTER_ZONE){drawFooter(doc,currentPage,totalPages,variant);doc.addPage();currentPage++;drawWatermark(doc);y=drawHeader(doc)+9;y=drawTH(y);}if(i%2===0){doc.setFillColor(249,247,243);doc.rect(M,y,CW,RH,"F");}const it=items[i];const tY=y+RH/2+1;doc.setTextColor(...CHARCOAL);doc.setFont("helvetica","normal");doc.setFontSize(7);doc.text(`${i+1}`,colX[0],tY);doc.text(it.label.length>55?it.label.slice(0,52)+"…":it.label,colX[1],tY);doc.text(it.responseValue!=null?`${it.responseValue}`:"—",colX[2],tY);doc.setFont("helvetica","bold");doc.text(it.points!=null?`${it.points}`:"—",colX[3],tY);if(hasFlags&&it.flagLabel){doc.setTextColor(...RED);doc.setFontSize(6.5);doc.text(`! ${it.flagLabel}`,colX[4],tY);}y+=RH;}
  y=checkPage(y,RH+2);doc.setFillColor(...SAGE);doc.roundedRect(M,y,CW,RH,1,1,"F");doc.setTextColor(...WHITE);doc.setFont("helvetica","bold");doc.setFontSize(8);doc.text("TOTAL",colX[1],y+RH/2+1.5);doc.text(`${score}${maxStr}`,colX[3],y+RH/2+1.5);y+=RH+6;

  // Scoring Transparency (therapist only) — WITH CALCULATION
  if(variant==="therapist"){
    y=checkPage(y,45);
    doc.setTextColor(...NAVY);doc.setFont("times","bold");doc.setFontSize(12);doc.text("Scoring Transparency",M,y);y+=7;
    doc.setFont("helvetica","normal");doc.setFontSize(8);doc.setTextColor(...CHARCOAL);
    doc.text("Scoring method: Sum",M,y);y+=5;
    doc.text(`Instrument: ${TITLE}`,M,y);y+=5;

    // Calculation
    const answered=items.filter(it=>it.points!==null);
    if(answered.length>0){
      y=checkPage(y,14);
      doc.setFont("helvetica","bold");doc.setFontSize(8);doc.setTextColor(...NAVY);
      doc.text("Calculation:",M,y);y+=5;
      doc.setFont("courier","normal");doc.setFontSize(7);doc.setTextColor(...CHARCOAL);
      const parts=answered.map(it=>`${it.points}`);
      const formula=parts.join(" + ")+` = ${score}`;
      const fLines=doc.splitTextToSize(formula,CW-6);
      for(const fl of fLines){y=checkPage(y,4);doc.text(fl,M+4,y);y+=4;}
      y+=2;

      doc.setFont("helvetica","normal");doc.setFontSize(7);doc.setTextColor(...CHARCOAL);
      for(let i=0;i<answered.length;i++){
        y=checkPage(y,4);
        const it=answered[i];
        const ls=it.label.length>45?it.label.slice(0,42)+"…":it.label;
        doc.text(`  Item ${i+1}: "${ls}" → response ${it.responseValue} = ${it.points} pts`,M+2,y);
        y+=4;
      }
      y+=3;
      doc.setFont("helvetica","normal");doc.setFontSize(8);
      doc.text(`Maximum possible score: ${maxPS}`,M,y);y+=5;
    }

    // Bands with highlight
    const bands=[{min:0,max:4,label:"minimal"},{min:5,max:9,label:"mild"},{min:10,max:14,label:"moderate"},{min:15,max:19,label:"moderately_severe"},{min:20,max:27,label:"severe"}];
    y=checkPage(y,8+bands.length*4);
    doc.setFont("helvetica","bold");doc.setFontSize(8);doc.setTextColor(...NAVY);
    doc.text("Severity bands (per instrument definition):",M,y);y+=5;
    doc.setFont("helvetica","normal");doc.setTextColor(...CHARCOAL);
    for(const band of bands){
      y=checkPage(y,5);
      const isMatch=score>=band.min&&score<=band.max;
      if(isMatch){
        doc.setFillColor(247,250,248);doc.roundedRect(M,y-3,CW,5,0.5,0.5,"F");
        doc.setDrawColor(...SAGE);doc.setLineWidth(0.3);doc.roundedRect(M,y-3,CW,5,0.5,0.5,"S");
        doc.setFont("helvetica","bold");
        doc.text(`  ${band.min}–${band.max}: ${band.label}  ← score ${score} falls here`,M+4,y);
        doc.setFont("helvetica","normal");
      } else {
        doc.text(`  ${band.min}–${band.max}: ${band.label}`,M+4,y);
      }
      y+=4;
    }
    y+=3;
  }

  // Clinical flags (therapist)
  if(variant==="therapist"){
    const flagged=items.filter(it=>it.flagLabel);
    if(flagged.length>0){
      y=checkPage(y,20);doc.setTextColor(...NAVY);doc.setFont("times","bold");doc.setFontSize(12);doc.text("Clinical Flags",M,y);y+=7;
      for(const fi of flagged){y=checkPage(y,12);doc.setFillColor(255,243,224);doc.roundedRect(M,y,CW,10,1.5,1.5,"F");doc.setTextColor(230,81,0);doc.setFont("helvetica","bold");doc.setFontSize(7.5);doc.text(`! ${fi.flagLabel}`,M+3,y+4);doc.setFont("helvetica","normal");doc.setFontSize(7);doc.setTextColor(...CHARCOAL);doc.text(`Item: ${fi.label} · Response value: ${fi.responseValue}`,M+3,y+8);y+=12;}
      y+=4;
    }
  }

  // Notice
  y=checkPage(y,40);
  if(variant==="patient"){
    const padX=6,padTop=7,padBottom=7,titleLineH=6,bodyLineH=4;
    const bodyLines=[`The score presented above reflects your responses to a validated clinical instrument`,`(${TITLE}) and is provided for informational purposes only. It does not`,`constitute a diagnosis, clinical assessment, or treatment recommendation.`,``,`Please discuss these results with your therapist or a qualified mental health professional.`,``,`This document does not replace a clinical evaluation.`];
    const nH=padTop+titleLineH+bodyLines.length*bodyLineH+padBottom;
    doc.setFillColor(255,248,225);doc.roundedRect(M,y,CW,nH,2,2,"F");doc.setDrawColor(240,208,96);doc.setLineWidth(0.4);doc.roundedRect(M,y,CW,nH,2,2,"S");
    let ny=y+padTop;doc.setTextColor(...NAVY);doc.setFont("helvetica","bold");doc.setFontSize(9);doc.text("Important Notice",M+padX,ny);ny+=titleLineH;doc.setFont("helvetica","normal");doc.setFontSize(7.5);doc.setTextColor(...CHARCOAL);for(const l of bodyLines){doc.text(l,M+padX,ny);ny+=bodyLineH;}
  } else {
    doc.setTextColor(...NAVY);doc.setFont("times","bold");doc.setFontSize(12);doc.text("Notices",M,y);y+=7;
    doc.setFont("helvetica","normal");doc.setFontSize(7.5);doc.setTextColor(...CHARCOAL);
    const notices=[`This document is a platform-generated scoring summary for ${TITLE}. Scores are computed using the instrument's published scoring algorithm. Item-level data is provided for transparency. Clinical interpretation remains the sole responsibility of the treating clinician.`,``,`Follow applicable legal and professional guidelines.`];
    for(const n of notices){const w=doc.splitTextToSize(n,CW-2);for(const l of w){y=checkPage(y,5);doc.setTextColor(...CHARCOAL);doc.setFont("helvetica","normal");doc.setFontSize(7.5);doc.text(l,M,y);y+=4;}}
  }

  drawFooter(doc,currentPage,totalPages,variant);
  totalPages=currentPage;
  const pc=(doc as any).internal.getNumberOfPages();
  for(let p=1;p<=pc;p++){doc.setPage(p);doc.setFillColor(255,255,255);doc.rect(PAGE_W/2-15,PAGE_H-16,30,6,"F");doc.setFont("helvetica","normal");doc.setFontSize(7);doc.setTextColor(...CHARCOAL);const pg=`${p} / ${totalPages}`;doc.text(pg,(PAGE_W-doc.getTextWidth(pg))/2,PAGE_H-12);}
  return doc.output("arraybuffer");
}

fs.writeFileSync("/mnt/documents/scale-result-patient-v2.pdf", Buffer.from(build("patient")));
fs.writeFileSync("/mnt/documents/scale-result-therapist-v2.pdf", Buffer.from(build("therapist")));
console.log("Done");
