/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PTokenRouteImport } from './routes/p.$token'
import { Route as HTokenRouteImport } from './routes/h.$token'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedWorksheetsRouteImport } from './routes/_authenticated/worksheets'
import { Route as AuthenticatedWelcomeRouteImport } from './routes/_authenticated/welcome'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedScalesRouteImport } from './routes/_authenticated/scales'
import { Route as AuthenticatedPatientsRouteImport } from './routes/_authenticated/patients'
import { Route as AuthenticatedMindfulnessRouteImport } from './routes/_authenticated/mindfulness'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as AuthenticatedSettingsWorkspaceRouteImport } from './routes/_authenticated/settings.workspace'
import { Route as AuthenticatedSettingsSecurityRouteImport } from './routes/_authenticated/settings.security'
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/_authenticated/settings.profile'
import { Route as AuthenticatedSettingsBillingRouteImport } from './routes/_authenticated/settings.billing'
import { Route as AuthenticatedPatientsDeletedRouteImport } from './routes/_authenticated/patients.deleted'
import { Route as AuthenticatedPatientsIdRouteImport } from './routes/_authenticated/patients.$id'
import { Route as AuthenticatedDevRoadmapRouteImport } from './routes/_authenticated/dev.roadmap'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as ApiPublicHooksPurgePatientsRouteImport } from './routes/api/public/hooks/purge-patients'
import { Route as ApiPublicHooksAggregateAnalyticsRouteImport } from './routes/api/public/hooks/aggregate-analytics'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PTokenRoute = PTokenRouteImport.update({
  id: '/p/$token',
  path: '/p/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const HTokenRoute = HTokenRouteImport.update({
  id: '/h/$token',
  path: '/h/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorksheetsRoute = AuthenticatedWorksheetsRouteImport.update({
  id: '/worksheets',
  path: '/worksheets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWelcomeRoute = AuthenticatedWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedScalesRoute = AuthenticatedScalesRouteImport.update({
  id: '/scales',
  path: '/scales',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPatientsRoute = AuthenticatedPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMindfulnessRoute =
  AuthenticatedMindfulnessRouteImport.update({
    id: '/mindfulness',
    path: '/mindfulness',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsWorkspaceRoute =
  AuthenticatedSettingsWorkspaceRouteImport.update({
    id: '/workspace',
    path: '/workspace',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsSecurityRoute =
  AuthenticatedSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsBillingRoute =
  AuthenticatedSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedPatientsDeletedRoute =
  AuthenticatedPatientsDeletedRouteImport.update({
    id: '/deleted',
    path: '/deleted',
    getParentRoute: () => AuthenticatedPatientsRoute,
  } as any)
const AuthenticatedPatientsIdRoute = AuthenticatedPatientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedPatientsRoute,
} as any)
const AuthenticatedDevRoadmapRoute = AuthenticatedDevRoadmapRouteImport.update({
  id: '/dev/roadmap',
  path: '/dev/roadmap',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/admin/analytics',
    path: '/admin/analytics',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicHooksPurgePatientsRoute =
  ApiPublicHooksPurgePatientsRouteImport.update({
    id: '/api/public/hooks/purge-patients',
    path: '/api/public/hooks/purge-patients',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAggregateAnalyticsRoute =
  ApiPublicHooksAggregateAnalyticsRouteImport.update({
    id: '/api/public/hooks/aggregate-analytics',
    path: '/api/public/hooks/aggregate-analytics',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/mindfulness': typeof AuthenticatedMindfulnessRoute
  '/patients': typeof AuthenticatedPatientsRouteWithChildren
  '/scales': typeof AuthenticatedScalesRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/welcome': typeof AuthenticatedWelcomeRoute
  '/worksheets': typeof AuthenticatedWorksheetsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/h/$token': typeof HTokenRoute
  '/p/$token': typeof PTokenRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/dev/roadmap': typeof AuthenticatedDevRoadmapRoute
  '/patients/$id': typeof AuthenticatedPatientsIdRoute
  '/patients/deleted': typeof AuthenticatedPatientsDeletedRoute
  '/settings/billing': typeof AuthenticatedSettingsBillingRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/settings/workspace': typeof AuthenticatedSettingsWorkspaceRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/api/public/hooks/aggregate-analytics': typeof ApiPublicHooksAggregateAnalyticsRoute
  '/api/public/hooks/purge-patients': typeof ApiPublicHooksPurgePatientsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/mindfulness': typeof AuthenticatedMindfulnessRoute
  '/patients': typeof AuthenticatedPatientsRouteWithChildren
  '/scales': typeof AuthenticatedScalesRoute
  '/welcome': typeof AuthenticatedWelcomeRoute
  '/worksheets': typeof AuthenticatedWorksheetsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/h/$token': typeof HTokenRoute
  '/p/$token': typeof PTokenRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/dev/roadmap': typeof AuthenticatedDevRoadmapRoute
  '/patients/$id': typeof AuthenticatedPatientsIdRoute
  '/patients/deleted': typeof AuthenticatedPatientsDeletedRoute
  '/settings/billing': typeof AuthenticatedSettingsBillingRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/settings/workspace': typeof AuthenticatedSettingsWorkspaceRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/api/public/hooks/aggregate-analytics': typeof ApiPublicHooksAggregateAnalyticsRoute
  '/api/public/hooks/purge-patients': typeof ApiPublicHooksPurgePatientsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/mindfulness': typeof AuthenticatedMindfulnessRoute
  '/_authenticated/patients': typeof AuthenticatedPatientsRouteWithChildren
  '/_authenticated/scales': typeof AuthenticatedScalesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/welcome': typeof AuthenticatedWelcomeRoute
  '/_authenticated/worksheets': typeof AuthenticatedWorksheetsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/h/$token': typeof HTokenRoute
  '/p/$token': typeof PTokenRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/dev/roadmap': typeof AuthenticatedDevRoadmapRoute
  '/_authenticated/patients/$id': typeof AuthenticatedPatientsIdRoute
  '/_authenticated/patients/deleted': typeof AuthenticatedPatientsDeletedRoute
  '/_authenticated/settings/billing': typeof AuthenticatedSettingsBillingRoute
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/_authenticated/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/_authenticated/settings/workspace': typeof AuthenticatedSettingsWorkspaceRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/api/public/hooks/aggregate-analytics': typeof ApiPublicHooksAggregateAnalyticsRoute
  '/api/public/hooks/purge-patients': typeof ApiPublicHooksPurgePatientsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard'
    | '/library'
    | '/mindfulness'
    | '/patients'
    | '/scales'
    | '/settings'
    | '/welcome'
    | '/worksheets'
    | '/auth/callback'
    | '/h/$token'
    | '/p/$token'
    | '/admin/analytics'
    | '/dev/roadmap'
    | '/patients/$id'
    | '/patients/deleted'
    | '/settings/billing'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/workspace'
    | '/api/public/stripe-webhook'
    | '/admin/'
    | '/settings/'
    | '/api/public/hooks/aggregate-analytics'
    | '/api/public/hooks/purge-patients'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard'
    | '/library'
    | '/mindfulness'
    | '/patients'
    | '/scales'
    | '/welcome'
    | '/worksheets'
    | '/auth/callback'
    | '/h/$token'
    | '/p/$token'
    | '/admin/analytics'
    | '/dev/roadmap'
    | '/patients/$id'
    | '/patients/deleted'
    | '/settings/billing'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/workspace'
    | '/api/public/stripe-webhook'
    | '/admin'
    | '/settings'
    | '/api/public/hooks/aggregate-analytics'
    | '/api/public/hooks/purge-patients'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/dashboard'
    | '/_authenticated/library'
    | '/_authenticated/mindfulness'
    | '/_authenticated/patients'
    | '/_authenticated/scales'
    | '/_authenticated/settings'
    | '/_authenticated/welcome'
    | '/_authenticated/worksheets'
    | '/auth/callback'
    | '/h/$token'
    | '/p/$token'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/dev/roadmap'
    | '/_authenticated/patients/$id'
    | '/_authenticated/patients/deleted'
    | '/_authenticated/settings/billing'
    | '/_authenticated/settings/profile'
    | '/_authenticated/settings/security'
    | '/_authenticated/settings/workspace'
    | '/api/public/stripe-webhook'
    | '/_authenticated/admin/'
    | '/_authenticated/settings/'
    | '/api/public/hooks/aggregate-analytics'
    | '/api/public/hooks/purge-patients'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  HTokenRoute: typeof HTokenRoute
  PTokenRoute: typeof PTokenRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
  ApiPublicHooksAggregateAnalyticsRoute: typeof ApiPublicHooksAggregateAnalyticsRoute
  ApiPublicHooksPurgePatientsRoute: typeof ApiPublicHooksPurgePatientsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$token': {
      id: '/p/$token'
      path: '/p/$token'
      fullPath: '/p/$token'
      preLoaderRoute: typeof PTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/h/$token': {
      id: '/h/$token'
      path: '/h/$token'
      fullPath: '/h/$token'
      preLoaderRoute: typeof HTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/worksheets': {
      id: '/_authenticated/worksheets'
      path: '/worksheets'
      fullPath: '/worksheets'
      preLoaderRoute: typeof AuthenticatedWorksheetsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/welcome': {
      id: '/_authenticated/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AuthenticatedWelcomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scales': {
      id: '/_authenticated/scales'
      path: '/scales'
      fullPath: '/scales'
      preLoaderRoute: typeof AuthenticatedScalesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patients': {
      id: '/_authenticated/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AuthenticatedPatientsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mindfulness': {
      id: '/_authenticated/mindfulness'
      path: '/mindfulness'
      fullPath: '/mindfulness'
      preLoaderRoute: typeof AuthenticatedMindfulnessRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/workspace': {
      id: '/_authenticated/settings/workspace'
      path: '/workspace'
      fullPath: '/settings/workspace'
      preLoaderRoute: typeof AuthenticatedSettingsWorkspaceRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/security': {
      id: '/_authenticated/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthenticatedSettingsSecurityRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/billing': {
      id: '/_authenticated/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AuthenticatedSettingsBillingRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/patients/deleted': {
      id: '/_authenticated/patients/deleted'
      path: '/deleted'
      fullPath: '/patients/deleted'
      preLoaderRoute: typeof AuthenticatedPatientsDeletedRouteImport
      parentRoute: typeof AuthenticatedPatientsRoute
    }
    '/_authenticated/patients/$id': {
      id: '/_authenticated/patients/$id'
      path: '/$id'
      fullPath: '/patients/$id'
      preLoaderRoute: typeof AuthenticatedPatientsIdRouteImport
      parentRoute: typeof AuthenticatedPatientsRoute
    }
    '/_authenticated/dev/roadmap': {
      id: '/_authenticated/dev/roadmap'
      path: '/dev/roadmap'
      fullPath: '/dev/roadmap'
      preLoaderRoute: typeof AuthenticatedDevRoadmapRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/hooks/purge-patients': {
      id: '/api/public/hooks/purge-patients'
      path: '/api/public/hooks/purge-patients'
      fullPath: '/api/public/hooks/purge-patients'
      preLoaderRoute: typeof ApiPublicHooksPurgePatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/aggregate-analytics': {
      id: '/api/public/hooks/aggregate-analytics'
      path: '/api/public/hooks/aggregate-analytics'
      fullPath: '/api/public/hooks/aggregate-analytics'
      preLoaderRoute: typeof ApiPublicHooksAggregateAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedPatientsRouteChildren {
  AuthenticatedPatientsIdRoute: typeof AuthenticatedPatientsIdRoute
  AuthenticatedPatientsDeletedRoute: typeof AuthenticatedPatientsDeletedRoute
}

const AuthenticatedPatientsRouteChildren: AuthenticatedPatientsRouteChildren = {
  AuthenticatedPatientsIdRoute: AuthenticatedPatientsIdRoute,
  AuthenticatedPatientsDeletedRoute: AuthenticatedPatientsDeletedRoute,
}

const AuthenticatedPatientsRouteWithChildren =
  AuthenticatedPatientsRoute._addFileChildren(
    AuthenticatedPatientsRouteChildren,
  )

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsBillingRoute: typeof AuthenticatedSettingsBillingRoute
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute
  AuthenticatedSettingsSecurityRoute: typeof AuthenticatedSettingsSecurityRoute
  AuthenticatedSettingsWorkspaceRoute: typeof AuthenticatedSettingsWorkspaceRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsBillingRoute: AuthenticatedSettingsBillingRoute,
  AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
  AuthenticatedSettingsSecurityRoute: AuthenticatedSettingsSecurityRoute,
  AuthenticatedSettingsWorkspaceRoute: AuthenticatedSettingsWorkspaceRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedMindfulnessRoute: typeof AuthenticatedMindfulnessRoute
  AuthenticatedPatientsRoute: typeof AuthenticatedPatientsRouteWithChildren
  AuthenticatedScalesRoute: typeof AuthenticatedScalesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedWelcomeRoute: typeof AuthenticatedWelcomeRoute
  AuthenticatedWorksheetsRoute: typeof AuthenticatedWorksheetsRoute
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedDevRoadmapRoute: typeof AuthenticatedDevRoadmapRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedMindfulnessRoute: AuthenticatedMindfulnessRoute,
  AuthenticatedPatientsRoute: AuthenticatedPatientsRouteWithChildren,
  AuthenticatedScalesRoute: AuthenticatedScalesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedWelcomeRoute: AuthenticatedWelcomeRoute,
  AuthenticatedWorksheetsRoute: AuthenticatedWorksheetsRoute,
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedDevRoadmapRoute: AuthenticatedDevRoadmapRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  HTokenRoute: HTokenRoute,
  PTokenRoute: PTokenRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
  ApiPublicHooksAggregateAnalyticsRoute: ApiPublicHooksAggregateAnalyticsRoute,
  ApiPublicHooksPurgePatientsRoute: ApiPublicHooksPurgePatientsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
