// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import { supabase as browserSupabase } from './client'
import type { Database } from './types'

/**
 * Client-side step: pega o access_token da sessão Supabase no browser
 * e injeta como header `Authorization: Bearer <token>` antes do request
 * sair pro server. Roda só no client (no SSR não há sessão).
 */
const attachSupabaseToken = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    let token: string | undefined;
    if (typeof window !== 'undefined') {
      const { data } = await browserSupabase.auth.getSession();
      token = data.session?.access_token;
    }
    return next({
      sendContext: {},
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    });
  },
);

const validateSupabaseToken = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    const SUPABASE_URL = process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      throw new Response(
        'Missing Supabase environment variables. Ensure SUPABASE_URL and SUPABASE_PUBLISHABLE_KEY are set.',
        { status: 500 }
      );
    }

    const request = getRequest();

    if (!request?.headers) {
      throw new Response('Unauthorized: No request headers available', { status: 401 });
    }

    const authHeader = request.headers.get('authorization');

    if (!authHeader) {
      throw new Response('Unauthorized: No authorization header provided', { status: 401 });
    }

    if (!authHeader.startsWith('Bearer ')) {
      throw new Response('Unauthorized: Only Bearer tokens are supported', { status: 401 });
    }

    const token = authHeader.replace('Bearer ', '');
    if (!token) {
      throw new Response('Unauthorized: No token provided', { status: 401 });
    }

    const supabase = createClient<Database>(
      SUPABASE_URL!,
      SUPABASE_PUBLISHABLE_KEY!,
      {
        global: {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      }
    );

    const { data, error } = await supabase.auth.getClaims(token);
    if (error || !data?.claims) {
      throw new Response('Unauthorized: Invalid token', { status: 401 });
    }

    if (!data.claims.sub) {
      throw new Response('Unauthorized: No user ID found in token', { status: 401 });
    }

    return next({
      context: {
        supabase,
        userId: data.claims.sub,
        claims: data.claims,
      },
    })
  }
)

export const requireSupabaseAuth = createMiddleware({ type: 'function' })
  .middleware([attachSupabaseToken])
  .server(async ({ next }) => {
    return validateSupabaseToken._types ? next() : next();
  });

// Compose: o `requireSupabaseAuth` real precisa rodar attach (client) +
// validate (server) em sequência. Reexport via composição de middleware.
export const requireSupabaseAuthChain = [attachSupabaseToken, validateSupabaseToken];
